Week 2/railsgirls/config/routes.rb
Railsgirls::Application.routes.draw do
  resources :ideas
  root to: 'ideas#index'

end

Week 2/railsgirls/app/models/idea.rb
class Idea < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  attr_accessible :description, :name, :picture
end

Week 2/railsgirls/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

Week 2/railsgirls/app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ideas }
    end
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @idea = Idea.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/new
  # GET /ideas/new.json
  def new
    @idea = Idea.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/1/edit
  def edit
    @idea = Idea.find(params[:id])
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(params[:idea])

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render json: @idea, status: :created, location: @idea }
      else
        format.html { render action: "new" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ideas/1
  # PUT /ideas/1.json
  def update
    @idea = Idea.find(params[:id])

    respond_to do |format|
      if @idea.update_attributes(params[:idea])
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy

    respond_to do |format|
      format.html { redirect_to ideas_url }
      format.json { head :no_content }
    end
  end
end

Week 2/railsgirls/app/helpers/application_helper.rb
module ApplicationHelper
end

Week 2/railsgirls/app/helpers/ideas_helper.rb
module IdeasHelper
end

Week 2/railsgirls/app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br />
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Week 2/railsgirls/app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

Week 2/railsgirls/app/views/ideas/index.html.erb
<h1>Listing ideas</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Picture</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ideas.each do |idea| %>
  <tr>
    <td><%= idea.name %></td>
    <td><%= idea.description %></td>
    <td><%= idea.picture %></td>
    <td><%= link_to 'Show', idea %></td>
    <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
    <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Idea', new_idea_path %>

Week 2/railsgirls/app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

Week 2/railsgirls/app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @idea.name %>
</p>

<p>
  <b>Description:</b>
  <%= @idea.description %>
</p>

<p>
  <b>Picture:</b>
  <%= image_tag(@idea.picture_url, width: 300) if @idea.picture.present? %>
</p>


<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>

Week 2/railsgirls/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railsgirls</title>
  <link rel="stylesheet" href="http://railsgirls.com/assets/bootstrap.css">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top">
<div class="navbar-inner">
  <div class="container">
    <a class="brand" href="/">The Idea app</a>
    <ul class="nav">
      <li class="active"><a href="/ideas">Ideas</a></li>
    </ul>
  </div>
</div>
</div>

<div class="container">
  <%= yield %>
</div>

<footer>
  <div class="container">
    Rails Girls 2013
  </div>
</footer>

</body>
</html>